//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 Ucom.rc 使用
//
#define IDD_UCOM_DIALOG                 102
#define IDD_GRAPH                       129
#define IDD_ENCODER                     130
#define IDD_XSEND                       131
#define IDD_WATCH                       132
#define IDD_FILE_LOAD                   133
#define IDB_SwOn                        135
#define IDB_LOGO                        136
#define IDB_SwOff                       137
#define IDI_ICON1                       140
#define IDR_MENU_ToolsBox               141
#define IDD_GraphFull                   142
#define IDD_UART                        143
#define IDD_NET                         145
#define IDD_DATACRC                     146
#define IDD_CMDCTL                      149
#define IDD_YOUGUCTL                    150
#define IDB_SwRedOn                     151
#define IDB_SwBlueOn                    152
#define IDC_BtnHelp                     1000
#define IDC_EditTxData                  1001
#define IDC_BtnOpen                     1002
#define IDC_BtnSend                     1003
#define IDC_CbUartPort                  1005
#define IDC_TABEx                       1006
#define IDC_CbUartBaudrate              1007
#define IDC_CANVAS                      1009
#define IDC_CbUartStopbit               1010
#define IDC_GrpGraph                    1010
#define IDC_CbUartECC                   1011
#define IDC_EdbData0                    1011
#define IDC_CbUartDatabit               1012
#define IDC_EdbData1                    1012
#define IDC_Launch                      1013
#define IDC_EdbData2                    1013
#define IDC_EdbData3                    1014
#define IDC_BtnClearGraph               1015
#define IDC_EdbData4                    1015
#define IDC_BtnEncoder                  1016
#define IDC_EdbData5                    1016
#define IDC_EdbData6                    1017
#define IDC_EdbData7                    1018
#define IDC_RADIO1                      1019
#define IDC_EdbData8                    1019
#define IDC_RADIO2                      1020
#define IDC_EdbData9                    1020
#define IDC_GrpEnc                      1021
#define IDC_EdbData10                   1021
#define IDC_RADIO3                      1022
#define IDC_ListWatch                   1025
#define IDC_PicUartStatus               1027
#define IDC_EdbListItem                 1028
#define IDC_ChkHexList                  1029
#define IDC_BtnWatch                    1030
#define IDC_BtnClearList                1031
#define IDC_BtnClearRecv                1032
#define IDC_GrpRecv                     1033
#define IDC_EditMaxListNum              1033
#define IDC_GrpRS                       1033
#define IDC_BtnClearSend                1034
#define IDC_BtnSend1                    1037
#define IDC_BtnSend2                    1038
#define IDC_BtnSend3                    1039
#define IDC_BtnSend4                    1040
#define IDC_GrpSend                     1041
#define IDC_BtnSend5                    1041
#define IDC_BtnSend6                    1042
#define IDC_BtnSend7                    1043
#define IDC_BtnSend8                    1044
#define IDC_CkbSendOnTime               1045
#define IDC_BtnSend9                    1045
#define IDC_EdbSendDelay                1046
#define IDC_BtnSend10                   1046
#define IDC_CkbFrameNewLine             1047
#define IDC_BtnClearnCnt                1048
#define IDC_CkbDispHex                  1049
#define IDC_CkbSendHex                  1050
#define IDC_EdbFullBytes                1051
#define IDC_CkbTimeXSend                1054
#define IDC_BtnIsDispRx                 1055
#define IDC_EdbTimeXSend                1055
#define IDC_BtnToolBox                  1056
#define IDC_EncInput                    1057
#define IDC_CkbXHex1                    1057
#define IDC_EncOuput                    1058
#define IDC_CkbXHex2                    1058
#define IDC_CkbXHex3                    1059
#define IDC_CkbXHex4                    1060
#define IDC_EncClear                    1061
#define IDC_CkbXHex5                    1061
#define IDC_CkbXHex6                    1062
#define IDC_CkbXHex7                    1063
#define IDC_CkbXHex8                    1064
#define IDC_CkbXHex9                    1065
#define IDC_BtnWinSize                  1066
#define IDC_CkbXHex10                   1066
#define IDC_EdbXDetail                  1067
#define IDC_BtnTrans                    1068
#define IDC_RichRx                      1070
#define IDC_CkbXNewLine                 1070
#define IDC_BtnBackColor                1071
#define IDC_CbTransNum                  1071
#define IDC_BtnFontColor                1072
#define IDC_BtnStartGraph               1072
#define IDC_BtnFont                     1073
#define IDC_CkbXHotKey                  1073
#define IDC_BtnGraphFull                1073
#define IDC_CkbRxFullClc                1074
#define IDC_PrgSend                     1074
#define IDC_BtnLoad                     1075
#define IDC_BtnSaveRx                   1076
#define IDC_BtnClearAll                 1077
#define IDC_EdbFileLog                  1077
#define IDC_BtnSendFile                 1078
#define IDC_CkbCMD                      1081
#define IDC_Chart                       1082
#define IDC_BUTTONgraph                 1083
#define IDC_GrpAXIS                     1084
#define IDC_RadYAxis                    1085
#define IDC_RadXAxis                    1086
#define IDC_CkbAxisScroll               1088
#define IDC_EdbAxisMax                  1091
#define IDC_EdbAxisMin                  1092
#define IDC_CkbAxisAuto                 1093
#define IDC_CkbAxisGrid                 1094
#define IDC_BtnGraphColor               1095
#define IDC_LstLineData                 1097
#define IDC_BtnLineColor                1099
#define IDC_CkbLineV                    1100
#define IDC_TxtLineP                    1101
#define IDC_CbLineWidth                 1102
#define IDC_CbLinePen                   1103
#define IDC_BtnSaveLine                 1104
#define IDC_ChartFull                   1105
#define IDC_TABSrc                      1109
#define IDC_IPDst                       1110
#define IDC_CbNetType                   1114
#define IDC_EditNetPortServer           1115
#define IDC_EditNetPortLocal            1116
#define IDC_NPicUartStatus              1117
#define IDC_BtnNetConnect               1118
#define IDC_TxtIPInfo                   1119
#define IDC_CbClient                    1120
#define IDC_TxtRecvCnt                  1133
#define IDC_TxtSendCnt                  1134
#define IDC_CkbDTR                      1138
#define IDC_CkbRTS                      1139
#define IDC_CkbDSR                      1140
#define IDC_EdbCRCDataIn                1140
#define IDC_CkbCTS                      1141
#define IDC_CbEncDec                    1141
#define ID_BtnRedOpen                   1142
#define ID_BtnGreenOpen                 1143
#define ID_BtnBlueOpen                  1144
#define IDC_SlidRedPwm                  1145
#define IDC_SlidGreenPwm                1146
#define IDC_SlidBluePwm                 1147
#define IDC_REDTEXT                     1148
#define IDC_REDTEXT2                    1149
#define IDC_GREENTEXT                   1149
#define IDC_BLUETEXT                    1150
#define IDC_ShowRed                     1151
#define IDC_ShowGreen                   1152
#define IDC_ShowBlue                    1153
#define IDC_PicRedState                 1154
#define IDC_PicGreenState               1155
#define IDC_PicBlueState                1157
#define ID_Update                       1158
#define IDC_btnLoadFile                 1161
#define IDC_UpdateLog                   1162
#define IDC_UpdateBar                   1163
#define ID_MeuCalc                      32776
#define ID_MeuDevManger                 32777
#define ID_MeuNotepad                   32778
#define ID_MenuReg                      32783
#define ID_MenuCmd                      32784
#define ID_MenuServ                     32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        153
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1164
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
